### like 함수
- 전달받은 배열과 동일한 shape으로 초기값을 설정하여 새 배열 생성

    - np.zeros_like() : 초기값을 0으로 가지는 배열 생성
    - np.ones_like() : 초기값을 1으로 가지는 배열 생성
    - np.full_like() : 초기값을 fill_value 값으로 가지는 배열 생성

In [3]:
import numpy as np

def np_print(arr):
    text = '''
    type : {}
    shape : {}
    ndim : {}
    dtype : {}
    array data : \n {}'''.format(type(arr), arr.shape, arr.ndim, arr.dtype, arr)
    print(text)

In [5]:
# ones_like()
# 2행 3열의 구조에서 1~6의 숫자로 구성된 배열

data = [[1,2,3],
        [4,5,6]]

arr1 = np.array(data)
np_print(arr1)


    type : <class 'numpy.ndarray'>
    shape : (2, 3)
    ndim : 2
    dtype : int32
    array data : 
 [[1 2 3]
 [4 5 6]]


In [6]:
# arr1의 내용이 아니라 껍데기 형태만 그대로 베껴와 1로 채웁니다.
arr2 = np.ones_like(arr1)
np_print(arr2)


    type : <class 'numpy.ndarray'>
    shape : (2, 3)
    ndim : 2
    dtype : int32
    array data : 
 [[1 1 1]
 [1 1 1]]
