### Ⅱ. 배열 생성 및 초기화
2. 범위와 조건이 있는 데이터를 가지는 1차원 배열 생성
    - np.linspace()
    - np.arange()
    - np.logspace()
#### 2-1. np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
- 시작값(start)부터 마지막값(stop) 사이의 범위에서 균등한 간격으로 일정 개수(num)개의 데이터를 가지는 배열 생성
- num : 데이터 개수, 기본값 = 50
- endpoint : 마지막값에 stop을 포함/제외하는 조건 지정, 기본값 = True(포함)
- retstep : True로 전달하면 (배열, 데이터 사이의 간격)의 데이터를 담은 tuple을 반환
- dtype : 배열의 데이터 타입을 지정, 기본값 = None

In [1]:
import numpy as np

def np_print(arr):
    text = '''
    type : {}
    shape : {}
    ndim : {}
    dtype : {}
    array data : \n {}'''.format(type(arr), arr.shape, arr.ndim, arr.dtype, arr)
    print(text)

In [2]:
# 기본값 
# 0 이상 1 이하의 범위에서 발생한 숫자 5개를 포함하는 배열

arr = np.linspace(0, 1, num = 5)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (5,)
    ndim : 1
    dtype : float64
    array data : 
 [0.   0.25 0.5  0.75 1.  ]


In [3]:
# endpoint를 False로 변환
# for문 실행시 끝값이 포함되지않는것처럼 이와 같으 스타일로 나타낼수 있음
arr = np.linspace(0, 1, num = 5, endpoint = False)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (5,)
    ndim : 1
    dtype : float64
    array data : 
 [0.  0.2 0.4 0.6 0.8]


In [8]:
# retstep -> 반환값이 tuple -> (배열객체, 간격값)

arr = np.linspace(0, 1, num = 5, retstep = True)
print(arr)

(array([0.  , 0.25, 0.5 , 0.75, 1.  ]), 0.25)


In [9]:
np_print(arr[0])


    type : <class 'numpy.ndarray'>
    shape : (5,)
    ndim : 1
    dtype : float64
    array data : 
 [0.   0.25 0.5  0.75 1.  ]


#### 2-1. np.arange(start=0, stop, step=1,  dtype=None)
- 시작값(start)부터 마지막값(stop) 사이의 범위에서 지정한 간격(step)으로 일정 개수(num)개의 데이터를 가지는 배열 생성
- 파이썬 내장함수 range()와 유사
- start : 시작값, 기본값 = 0
- stop : 마지막값으로 범위에 포함되지 않음
- step : 데이터 사이의 간격, 기본값 = 1
- dtype : 배열의 데이터 타입을 지정, 기본값 = None

In [10]:
list(range(5))

[0, 1, 2, 3, 4]

In [12]:
# 기본값 0 ~ 5 미만의 범위에서 1씩 증가하는 숫자(정수)를 가지는 배열
arr = np.arange(5)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (5,)
    ndim : 1
    dtype : int32
    array data : 
 [0 1 2 3 4]


In [15]:
# 시작, 끝, 간격
# 0이상 5미만의 범위에서 0.5씩 증가하는 숫자를 가지는 배열
arr = np.arange(0, 5, 0.5)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (10,)
    ndim : 1
    dtype : float64
    array data : 
 [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [17]:
# arrange() 메서드로 생성된 배열과 shape(1,5)인 배열은 동일해 보이지만
# shape와 dimension 이 다릅니다.
# 그냥 1차원 4개짜리 배열
arr = np.arange(1,5)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (4,)
    ndim : 1
    dtype : int32
    array data : 
 [1 2 3 4]


In [19]:
arr[0]

1

In [18]:
# 2차원의 1*4형의 배열
arr2 = arr.reshape(1,4)
np_print(arr2)


    type : <class 'numpy.ndarray'>
    shape : (1, 4)
    ndim : 2
    dtype : int32
    array data : 
 [[1 2 3 4]]


In [20]:
arr2[0]

array([1, 2, 3, 4])