In [1]:
### (공통) 라이브러리 불러오기 및 사용자 함수 정의
import numpy as np

def np_print(nparr):

    print('''
    type : {}
    shape : {}
    dimension : {}
    dtype : {}
    data :\n {}
    '''.format(type(nparr), nparr.shape, nparr.ndim, nparr.dtype, nparr))

2) 요소 추가
- np.append(arr, values, axis=None)
    - arr 마지막에 values를 추가
    - axis 지정하지 않는 경우(기본값) : 1차원 배열로 변형되어 결합
    - axis = 0 : 행 방향으로 결합 (단, 열의 개수가 동일해야 함)
    - axis = 1 : 열 방향으로 결합 (단, 행의 개수가 동일해야 함)
    - 원본 배열들에 반영되지 않음

In [6]:
# 1 이상 10 미만의 범위에서 1씩 증가하는 숫자로 3 * 3 구조의 배열 a 생성
# 10 이상 19 미만의 범위에서 1씩 증가하는 숫자로 3 * 3 구조의 배열 b 생성

a = np.arange(1,10).reshape(3,3)

b = np.arange(10,19).reshape(3,3)

np_print(a)
np_print(b)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    dimension : 2
    dtype : int32
    data :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
    

    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    dimension : 2
    dtype : int32
    data :
 [[10 11 12]
 [13 14 15]
 [16 17 18]]
    


In [7]:
# 2개의 배열 결합
# axis를 지정하지 않는 경우 : np.append(arr1, arr2) -> axis = None
# arr1, arr2 모두 1차원으로 변형해서 추가함
np.append(a, b)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [8]:
# 2개의 배열 결합
# axis = 0 : 행 단위 결합 : 열 개수는 3개로 동일
np.append(a, b, axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [9]:
# 2개의 배열 결합
# axis = 1 : 열 단위 결합 : 행 개수는 3개로 동일
np.append(a, b, axis = 1)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [17]:
# 열의 개수가 다은 배열과의 결합
# 구조상 axis = 1같은 모양만 가능함
c = np.arange(30, 45).reshape(3,5)
np_print(c)


    type : <class 'numpy.ndarray'>
    shape : (3, 5)
    dimension : 2
    dtype : int32
    data :
 [[30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]]
    


In [18]:
np.append(a,c, axis = 1)

array([[ 1,  2,  3, 30, 31, 32, 33, 34],
       [ 4,  5,  6, 35, 36, 37, 38, 39],
       [ 7,  8,  9, 40, 41, 42, 43, 44]])

In [20]:
# 이러면 결합방향을 맞춰달라고 에러메세지를 띄움
np.append(a,c, axis = 0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 5

In [21]:
# 행 단위로 결합할 수 있는 구조로 변경(resize 활용)
c.resize(5,3)
c

array([[30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [23]:
# 행 개수가 다른 배열과의 결합
d = np.arange(90, 102).reshape(4,3)
np_print(d)


    type : <class 'numpy.ndarray'>
    shape : (4, 3)
    dimension : 2
    dtype : int32
    data :
 [[ 90  91  92]
 [ 93  94  95]
 [ 96  97  98]
 [ 99 100 101]]
    


In [24]:
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [25]:
np.append(b,d, axis = 0)

array([[ 10,  11,  12],
       [ 13,  14,  15],
       [ 16,  17,  18],
       [ 90,  91,  92],
       [ 93,  94,  95],
       [ 96,  97,  98],
       [ 99, 100, 101]])

In [26]:
# 굳이 가로로 결합해야된다면 reshape, resize를 이용해서 바꾸기는 가능합니다.
np.append(b, d.reshape(3,4), axis = 1)

array([[ 10,  11,  12,  90,  91,  92,  93],
       [ 13,  14,  15,  94,  95,  96,  97],
       [ 16,  17,  18,  98,  99, 100, 101]])

- np.insert(arr, idx, values, axis=None)
    - 지정한 인덱스(idx)에 value를 추가
    - axis 지정하지 않는 경우(기본값) : 1차원 배열의 변형되고 해당 인덱스에 추가
    - axis = 0 : 행 방향으로 n번째 행에 추가
    - axis = 1 : 열 방향으로 n번째 열에 추가
    - 원본 배열에 반영되지 않음

In [27]:
# 1이상 10 미만 범위에서 1씩 증가하는 숫자로 3 * 3 구조의 배열 생성
arr = np.arange(1,10).reshape(3,3)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    dimension : 2
    dtype : int32
    data :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
    


In [28]:
# axis 지정하지 않는 경우 : arr를 1차원 배열로 변형한 후
# 변형된 배열의 지정 index에 값 추가
# 2차원 array를 1차원 array로 변형, 1번 인덱스에 100 추가
np.insert(arr, 1, 100)
# 9개에서 10개로 증가했기 떄문에  2차원 배열에서 해제됩니다.

array([  1, 100,   2,   3,   4,   5,   6,   7,   8,   9])

In [30]:
# axis = 0 : 행 방향응로 index번째 행을 추가
# a배열의 1번 인덱스 행에 100을 추가 -> 행의 요소 개수(열 개수)만큼 100이 추가됨
np.insert(arr, 1, 100, axis = 0)

array([[  1,   2,   3],
       [100, 100, 100],
       [  4,   5,   6],
       [  7,   8,   9]])

In [32]:
# axis = 1 : 열 방향으로 index번째 행을 추가
# a배열의 2번 인덱스 열에 200추가
np.insert(arr, 2, 200, axis = 1)

array([[  1,   2, 200,   3],
       [  4,   5, 200,   6],
       [  7,   8, 200,   9]])

In [35]:
# 요소마다 다른 값으로 행/열 추가
# 요소의 개수를 동일하게 작성 -> 축을 기준으로 요소개수 결정 -> axis로 축 설정
print(np.insert(arr, 2, [10, 20, 30], axis = 1))
print('-'*50)
print(np.insert(arr, 2, [10, 20, 30], axis = 0))

[[ 1  2 10  3]
 [ 4  5 20  6]
 [ 7  8 30  9]]
--------------------------------------------------
[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [ 7  8  9]]


3) 요소 삭제
- np.delete(arr, idx, axis=None)
    - 지정한 인덱스(idx)에 해당하는 요소를 삭제
    - axis 지정하지 않는 경우(기본값) : 1차원 배열로 변형되어 해당 인덱스에 해당하는 요소를 삭제
    - axis = 0 : 행 방향으로 n번째 행을 삭제
    - axis = 1 : 열 방향으로 n번째 열을 삭제
    - 원본 배열에 반영되지 않음

In [36]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
print(a.reshape(9))
print(np.ravel(a))

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [39]:
# axis를 지정하지 않는 경우 : 1차원 배열로 변환 -> 지정한 index에 해당하는 요소를 삭제
# a배열에 대해 1번 인덱스 요소를 삭제
# 숫자1을 삭제하는 것이 아닌 인덱스 1번항목을 삭제합니다.
np.delete(a,1)

array([1, 3, 4, 5, 6, 7, 8, 9])

In [40]:
# 삭제되어도 원본배열은 변경되지 않습니다.
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
# a배열 세로축으로 0번째 삭제
np.delete(a,0, axis = 0)

array([[4, 5, 6],
       [7, 8, 9]])

In [43]:
# a배열 가로축으로 0번째 삭제
np.delete(a,0, axis = 1)

array([[2, 3],
       [5, 6],
       [8, 9]])

4) 배열 결합
- np.concatenate((arr1, arr2, ...), axis=0)
    - axis = 0(기본값) : 행 방향으로 두 배열 결합 (단, 열의 개수가 동일)
    - axis = 1 : 열 방향으로 두 배열 결합 (단, 행의 개수가 동일)
    - 원본 배열들은 변경되지 않음

In [44]:
# 1이상 7미만의 범위에서 1씩 증가하는 숫자로 2 x 3 구조의 배열 a 생성
# 7이상 13미만의 범위에서 1씩 증가하는 숫자로 2 x 3 구조의 배열 b 생성
# 13이상 23미만의 범위에서 1씩 증가하는 숫자로 2 x 5 구조의 배열 c 생성(열개수 다름)
# 23이상 38미만의 범위에서 1씩 증가하는 숫자로 5 x 3 구조읩 배열 d 생성(행개수 다름)
a = np.arange(1, 7).reshape(2, 3)
b = np.arange(7, 13).reshape(2, 3)
c = np.arange(13, 23).reshape(2, 5)
d = np.arange(23, 38).reshape(5, 3)

In [45]:
print(a)
print('-'*50)

print(b)
print('-'*50)

print(c)
print('-'*50)

print(d)
print('-'*50)



[[1 2 3]
 [4 5 6]]
--------------------------------------------------
[[ 7  8  9]
 [10 11 12]]
--------------------------------------------------
[[13 14 15 16 17]
 [18 19 20 21 22]]
--------------------------------------------------
[[23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]
 [35 36 37]]
--------------------------------------------------


In [47]:
# axis = 0(기본값) : 행 방향으로 두 배열 결합
# np.append(a, b)
# [1,2,3,4,5,6,7,8,9,10,11,12]
np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [48]:
# axis = 1 : 열 방향으로 두 배열 결합
np.concatenate((a,b), axis = 1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [52]:
# 행 방향으로 결합 : 열 갯수가 동일 해야함
# np.concatenate((a,c)) -> 에러
np.concatenate((a,c), axis = 1)

array([[ 1,  2,  3, 13, 14, 15, 16, 17],
       [ 4,  5,  6, 18, 19, 20, 21, 22]])

In [51]:
# 열 방향으로 결합 : 행 갯수 동일
# np.concatenate((a,d), axis = 1) -> 에러
np.concatenate((a,d), axis = 0)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [23, 24, 25],
       [26, 27, 28],
       [29, 30, 31],
       [32, 33, 34],
       [35, 36, 37]])

- np.split(arr, indices_or_sections, axis=0)
    - axis = 0(기본값) : 행 단위로 분리
    - axis = 1 : 열 단위로 분리
    - 원본 배열은 변경되지 않음

In [54]:
a = np.arange(1, 37).reshape(6,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [59]:
# 균등하지 않게 행 기준으로 분리
np.split(a, [1,2,3], axis = 0)


[array([[1, 2, 3, 4, 5, 6]]),
 array([[ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18]]),
 array([[19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]])]

In [58]:
# 인덱싱 기능합니다.
np.split(a, [1,2,3], axis = 0)[0]

array([[1, 2, 3, 4, 5, 6]])

In [60]:
# 균등하게 분리
# 리스트로 넘기면 위치를 지정합니다.
# 스칼라 값을 엄기면 균등하게 갯수를 맞춰서 쪼갭니다.
# 스칼라 값이로 처리시 반드시 나눈 갯수가 정수로 떨어져야합니다.
np.split(a, 3, axis = 0)

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]),
 array([[25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]])]

In [62]:
np.split(a, 3, axis = 1)

[array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20],
        [25, 26],
        [31, 32]]),
 array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22],
        [27, 28],
        [33, 34]]),
 array([[ 5,  6],
        [11, 12],
        [17, 18],
        [23, 24],
        [29, 30],
        [35, 36]])]