In [2]:
### (공통) 라이브러리 불러오기 및 사용자 함수 정의
import numpy as np

def np_print(nparr):

    print('''
    type : {}
    shape : {}
    dimension : {}
    dtype : {}
    data :\n {}
    '''.format(type(nparr), nparr.shape, nparr.ndim, nparr.dtype, nparr))

#### 조건 색인(Boolean indexing)
- 배열의 요소에 대해 조건을 적용하여 True, False로 조건에 대한 결과 반환
- True에 해당하는 요소만 조회하여 조건을 만족하는 결과 반환

In [3]:
# 0 부터 23까지 1씩 증가하는 정수값을 가지는 1차원 배열 생성
a = np.arange(0, 24)
np_print(a)


    type : <class 'numpy.ndarray'>
    shape : (24,)
    dimension : 1
    dtype : int32
    data :
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
    


In [4]:
# 1차원 배열 슬라이싱 : 1번부터 4번까지 접근
a[1:5]

array([1, 2, 3, 4])

In [5]:
# 1번째 인덱스로부터 14번째 인덱스까지 2개씩 건너뛰며 접근
a[1:15:2]

array([ 1,  3,  5,  7,  9, 11, 13])

In [6]:
# 2차원 배열 생성
b = a.reshape(6,4)
np_print(b)


    type : <class 'numpy.ndarray'>
    shape : (6, 4)
    dimension : 2
    dtype : int32
    data :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
    


In [7]:
# 2차원 배열 슬라이싱 : 1행부터 4행까지 접근
# 로우우선 
# 2차원_array [행(:열:간격)]
b[0:4]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [8]:
# 1행부터 4행에 대해 2열부터 3열 까지 접근
b[1:5, 2:4]

array([[ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [9]:
# 2차원 배열 슬라이싱을 통한 값 수정
# 1행부터 4행에 대해 2열부터 3열까지 모든 배열에 대해서 수정
s_arr = b[1:5, 2:4]
s_arr

array([[ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [10]:
# 0번째 행과 마지막 열을 제외한 모든 값을 99로 수정
s_arr[1:, :-1] = 99
s_arr

array([[ 6,  7],
       [99, 11],
       [99, 15],
       [99, 19]])

In [11]:
# 얕은복사로 인한 원본 배열의 변경
# s_arr 의 변경으로 인한 오리지널 b도 같이 변경됨
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 99, 11],
       [12, 13, 99, 15],
       [16, 17, 99, 19],
       [20, 21, 22, 23]])

In [12]:
# 2차원 배열 슬라이싱 : 연속되지 않은 범위의 열에 대한 인덱싱
# step1. 전체 행에 대해서 접근
# step2. 여러 개의 열 인덱싱 배열 전달
# bd의 전체 행 + 1, 3번째 열
# b[행, 열]
b[:, [1,3]]

# 다른 방법
# b[:, 1:4:2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19],
       [21, 23]])

In [13]:
b[b%2 == 0]

array([ 0,  2,  4,  6,  8, 12, 16, 20, 22])

In [14]:
b[(b%2 == 0) & (b!=0)]

array([ 2,  4,  6,  8, 12, 16, 20, 22])

#### 연습문제

- 조건색인을 이용히야 공무원 시험의 합격자 평균을 구해보세요
- 합격점수는 60점입니다.

아래는 시험점수 결과입니다.

[31, 30, 55, 34, 83, 75, 86, 60, 94, 80, 42, 37, 73, 80, 30, 65, 34, 55, 56, 51]

In [15]:
pub_off_test = np.array([31, 30, 55, 34, 83, 75, 86, 60, 94, 80, 42, 37, 73, 80, 30, 65, 34, 55, 56, 51])
pub_off_test

array([31, 30, 55, 34, 83, 75, 86, 60, 94, 80, 42, 37, 73, 80, 30, 65, 34,
       55, 56, 51])

In [16]:
pub_off_test[pub_off_test >= 60].mean()

77.33333333333333

#### 배열 복사
- 인덱싱, 슬라이싱을 통해 반환된 배열은 원본 배열에 대해 독립적인 새로운 객체가 아닌
  원본 배열과 종속적인 객체
- 원본과 독립적인 복사본인 배열을 생성

In [17]:
a = [1,2,3]
a2 = [1,2,3]

In [18]:
# 얕은복사
b = a

In [19]:
# 깊은 복사 1
c = a2[:]

In [20]:
print(a, a2)

[1, 2, 3] [1, 2, 3]


In [21]:
b[0] = 10
c[0] = 10

In [22]:
print(a, a2)

[10, 2, 3] [1, 2, 3]


In [23]:
# 0~3까지 범위로 1씩 증가하는 2*2 구조 배열 생성
arr1 = np.arange(0,4).reshape(2,2)
np_print(arr1)



    type : <class 'numpy.ndarray'>
    shape : (2, 2)
    dimension : 2
    dtype : int32
    data :
 [[0 1]
 [2 3]]
    


In [24]:
# 깊은복사 2
arr2 = arr1.copy()

In [25]:
# 얕은복사
arr3 = arr1

In [26]:
arr2[0,0] = 100
arr2

array([[100,   1],
       [  2,   3]])

In [27]:
arr3

array([[0, 1],
       [2, 3]])

### 배열 변환
#### 1. 전치(Transpose)
- 배열의 행/열 인덱스가 바뀌는 변환
- 배열객체.T : 행/열 인덱스가 바뀐 새로운 배열을 반환하며 원본은 변경되지 않음

<img src='img/transpose.png' width='200' height='200' align='left'>

In [28]:
# 1이상 12이하의 값을 가지는 3*4 구조의 배열생성
arr1 = np.arange(1,13).reshape(3,4)
np_print(arr1)


    type : <class 'numpy.ndarray'>
    shape : (3, 4)
    dimension : 2
    dtype : int32
    data :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
    


In [29]:
# 배열절환
# 원본에는 영향 없음
arr1.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

### 2. 배열 형태 변경
- arr.ravel(), np.ravel(arr)
    - 다차원 배열을 1차원 배열로 변환
    - np.ravel() : 1차원으로 변환되는 결과는 원본 배열에 반영되지 않음
    - arr.ravel() : 1차원으로 변환하는 배열의 요소가 변경되면 원본 배열에도 반영됨
- arr.reshape(new_shape), np.reshape(arr, new_shape)
    - 원본 배열 객체의 구조(shape)를 변경
    - 변경하려는 구조의 전체 요소 개수와 원본 배열의 전체 요소 개수가 동일해야 함
    - 변경하려는 구조의 튜플 중 하나의 원소는 -1로 대체할 수 있고 다른 하나의 원소를 기준으로 계산되어 사용됨
    - reshape() 메서드가 반환하는 배열의 요소가 변경되면 원본 배열에도 반영됨

In [31]:
# 다차원 배열을 1차원 배열로 변환
arr2 = arr1.ravel()

In [37]:
print(arr1)
print('-'*50)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
--------------------------------------------------
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [39]:
# 변환 후 값 수정, 원본과 비교 (얕은복사로 적용됩니다.)
# arr2만 바꾸려면 arr을 새로 지정해주어야 합니다.
arr2[0]  = 10

print(arr1)
print('-'*50)
print(arr2)

[[10  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
--------------------------------------------------
[10  2  3  4  5  6  7  8  9 10 11 12]


In [40]:
# arr1을 6 * 2로 바꾸되 하나의 축에 대해 -1을 사용
arr3 = arr1.reshape(-1,2)
arr3

array([[10,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [41]:
# 변환 후 값 수정, 원본과 비교 

arr3[0] = [100, 200]

In [42]:
# 이 역시 얕은 복사로 얽혀있어 불변하게 하려면 
# 값을 따로 지정해주어야합니다.(새 변수에 저장)
arr1

array([[100, 200,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

#### 3. 요소 변경, 추가, 삭제
1) 요소 변경
- arr.resize(new_shape), np.resize(arr, new_shape)
    - 배열 메서드를 사용하면 원본 변경, np 함수를 사용하면 새로운 배열 반환
    - 배열의 구조(shape)를 변경하며 원본 배열의 요소 수와 동일하지 않아도 변경 가능
    - 변경되는 배열의 요소 수가 동일할 경우 : reshape() 메서드와 동일한 결과
    - 변경되는 배열의 요소 수가 더 많을 경우
        - np.resize(arr, new_shape) : 원본을 변경하지 않고, 모자란 부분을 기존 배열 값에서 복사해서 추가
        - arr.resize(new_shape) : 원본을 변경하고, 모자란 부분을 0으로 채움
        - 공통적으로 new_shape은 튜플로 추가
    - 변경되는 배열의 요소 수가 더 작을 경우 : 마지막 남은 요소 삭제

In [45]:
np.random.seed(20)

In [46]:
# 1이상 10미만의 범위의 랜덤 정수값으로 3*5 구조를 가진 배열 생성
arr = np.random.randint(1,10,(3,5))
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (3, 5)
    dimension : 2
    dtype : int32
    data :
 [[4 5 7 8 3]
 [1 7 9 6 4]
 [1 7 7 1 6]]
    


In [47]:
arr2 = np.random.randint(1, 10,(3,5))
np_print(arr2)


    type : <class 'numpy.ndarray'>
    shape : (3, 5)
    dimension : 2
    dtype : int32
    data :
 [[8 6 3 7 4]
 [4 1 7 3 4]
 [2 9 1 3 8]]
    


In [49]:
# 변경되는 배열의 요수 수가 동일한 경우 : reshape()와 동일하게 동작함
arr.resize(5,3)
arr.size

15

In [50]:
arr

array([[4, 5, 7],
       [8, 3, 1],
       [7, 9, 6],
       [4, 1, 7],
       [7, 1, 6]])

In [51]:
# 변경 후 배열의 요소갯수가 더 많아진 경우
# 모자라는 부분은 한번더 반복하여 계속 입력됨
arr3 = np.resize(arr2, (6,3))
np_print(arr3)


    type : <class 'numpy.ndarray'>
    shape : (6, 3)
    dimension : 2
    dtype : int32
    data :
 [[8 6 3]
 [7 4 4]
 [1 7 3]
 [4 2 9]
 [1 3 8]
 [8 6 3]]
    


In [52]:
# refcheck = False인 경우만 크기가 다를 때 남는 자리를 0으로 채웁니다.
arr.resize((6,3), refcheck = False)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (6, 3)
    dimension : 2
    dtype : int32
    data :
 [[4 5 7]
 [8 3 1]
 [7 9 6]
 [4 1 7]
 [7 1 6]
 [0 0 0]]
    


In [53]:
# 변경되는 배열의 요소 수가 더 적은 경우 : 마지막 남은 요소를 삭제
# 크기가 원본과  resize를 이용했을 때 다르면 refcheck = False를 반드시 넣습니다.
arr.resize((3,3), refcheck = False)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    dimension : 2
    dtype : int32
    data :
 [[4 5 7]
 [8 3 1]
 [7 9 6]]
    
