### 인덱싱(Indexing), 슬라이싱(Slicing)
#### 1. 인덱싱 : 하나의 요소에 대해 참조
- 각 차원에 따라 배열이 참조하는 인덱스의 개수가 다름
    - 1차원 배열 : 인덱스 1개
    - 2차원 배열 : 인덱스 2개

In [181]:
### (공통) 라이브러리 불러오기 및 사용자 함수 정의
import numpy as np

def np_print(nparr):

    print('''
    type : {}
    shape : {}
    dimension : {}
    dtype : {}
    data :\n {}
    '''.format(type(nparr), nparr.shape, nparr.ndim, nparr.dtype, nparr))

In [182]:
# 0부터 23까지 1씩 증가하느 값을 아이템으로 가지는 1차원 배열 생성
arr1 = np.arange(0, 24)
np_print(arr1)



    type : <class 'numpy.ndarray'>
    shape : (24,)
    dimension : 1
    dtype : int32
    data :
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
    


In [183]:
# 1차원 배열 인덱싱 : 1번 인덱스 요소 접근
print(arr1[1])

# 1차원 배열 인덱싱 : 1번 인덱스 마지막 요소 접근
print(arr1[-1])

1
23


In [184]:
# 1차원 배열 인덱싱을 통한 값 수정
# 23 -> 100으로 수정
arr1[-1] = 100
arr1

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22, 100])

In [185]:
# 배열 arr1을 이용하여 4 *6 형태의 2차원 배열을 만들기
arr2 = arr1.reshape(4,6)
np_print(arr2)


    type : <class 'numpy.ndarray'>
    shape : (4, 6)
    dimension : 2
    dtype : int32
    data :
 [[  0   1   2   3   4   5]
 [  6   7   8   9  10  11]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22 100]]
    


In [186]:
# 2차원 배열 인덱싱 : 2차원 배열 [행인덱스, (열인덱스)]
# 하나의 행에 접근 : 1행
arr2[0]

array([0, 1, 2, 3, 4, 5])

In [187]:
# arr2 의 1번 인덱스의 3번째 요소
arr2[1][3]

9

In [188]:
# 하나의 열에 접근 : 모든 행에 대해서 하나의 열에 접급
# 반환값 : 1차원 array
# 전체중에 1번째 컬럼만 가져옵니다. (0,1), (1,1), (2,1), (3,1)
arr2[:, 1]

array([ 1,  7, 13, 19])

In [189]:
# 하나의 값에 접근

# 기존방법
print(arr2[2][2])

# numpy에서만 적용가능한 방법
print(arr2[2,2])

14
14


In [190]:
# 여러개의 행 조회
# 0,3 이 아니라 이중으로 감싸게 되면 0번과 3번째 행을 가져옵니다.
# 괄호 하나와 여러개 다름에 주의할것
arr2[[0,3]]

array([[  0,   1,   2,   3,   4,   5],
       [ 18,  19,  20,  21,  22, 100]])

In [191]:
# 여러개 열 조회
# 로우는 전체범위인데 열은 0, 2번째만 가져옵니다.
arr2[:,[0,2]]

array([[ 0,  2],
       [ 6,  8],
       [12, 14],
       [18, 20]])

In [192]:
# 0번째, 2번째 로우의 3번째, 5번째 컬럼을 가져오세요
arr2

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22, 100]])

In [193]:
arr2[[0,2]][:, [3,5]]

array([[ 3,  5],
       [15, 17]])

In [194]:
arr2[[0,2]]

array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17]])

In [195]:
# 2차원 배열 인덱싱을 통한 값 수정
# 하나의 행/열에 대해 모두 동일한 값으로 수정 : 전달하는 값을 스칼라값으로 전달
# 서로 다른 값으로 수정 : 배열 구조에 맞춰서 자료 전달
# 하나의 값을 수정하는 예시
arr2[2] = 9
arr2

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [  9,   9,   9,   9,   9,   9],
       [ 18,  19,  20,  21,  22, 100]])

In [196]:
# 단일 값이 아닌 여러 값을 대입하고 싶을 때는?
arr2[1] = [9, 9, 9, 99, 99, 99]
np_print(arr2)


    type : <class 'numpy.ndarray'>
    shape : (4, 6)
    dimension : 2
    dtype : int32
    data :
 [[  0   1   2   3   4   5]
 [  9   9   9  99  99  99]
 [  9   9   9   9   9   9]
 [ 18  19  20  21  22 100]]
    


In [197]:
# 스칼라값이 아니라 하나의 값만 수정하고 싶다면..?
# arr2[1][2] = [7]
# arr2

In [198]:
# 3차원 배열 생성
# 구조 : 2개의 층(페이지, 면), 4행 3열
# np.arange() -> 24개의 size
arr3 = np.arange(0, 24).reshape(2, 4, 3)
np_print(arr3)


    type : <class 'numpy.ndarray'>
    shape : (2, 4, 3)
    dimension : 3
    dtype : int32
    data :
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
    


In [199]:
# 3차원 배열 인덱싱 : arr[면, 행, 열]
# 0번째 면(페이지)에 접근
arr3[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [200]:
# 첫 번째(0)면 , 1번행에 접근
arr3[0, 1]

array([3, 4, 5])

In [201]:
# 첫 번째(0)면 , 1번행에 접근, 0번 열에 접근
arr3[0, 1, 0]

3

In [202]:
# 3차원 배열 력시 배열 인덱싱으로 값 수정이 가능합니다.
# 스칼라 연산을 통한 동일한 값으로 수정
# arr3의 2번 면(1번 인덱스)를 0으로 일괄 변경

arr3[1] = 0
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]]])

In [203]:
# 하나의 면에 대해 서로 다른 값으로 수정 : 1번면, 1번행을 [1,2,3]으로 변경
arr3[1,1] = [1,2,3]
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[ 0,  0,  0],
        [ 1,  2,  3],
        [ 0,  0,  0],
        [ 0,  0,  0]]])

In [204]:
# 아니면 아예 3*4 형식으로 대입을 하는 방법도 있습니다.
arr3[0] = [[10, 20, 30],
           [40, 50, 60],
           [0, 0, 0],
           [0, 0, 0]]
arr3

array([[[10, 20, 30],
        [40, 50, 60],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 1,  2,  3],
        [ 0,  0,  0],
        [ 0,  0,  0]]])

In [205]:
# 인덱스 배열을 전달아혀 여러개의 요소 참조
# (기존 인덱싱 방법) 0번때 장 0행 0열, 1행 1열, 2행 2열 요소에 접근
print(arr3[0,0,0]) # 10
print(arr3[0,1,1]) # 50
print(arr3[0,2,2]) # 0


10
50
0


In [206]:
arr3

array([[[10, 20, 30],
        [40, 50, 60],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 1,  2,  3],
        [ 0,  0,  0],
        [ 0,  0,  0]]])

In [207]:
# 여러 개의 인덱싱을 배열로 전달
# (행0, 열0), (행1, 열1), (행2, 열2)
# 3차원 배열일 경우에 : [페이지, [[0,1,2], [0,1,2]]]
# arr3[면, 행, 열] -> 만약 여러 단위를 조회할때는 이중리스트로 입력
# 삼중리스트 입력시 이중리스트 요소 반복

arr3[0, [[0,1,2], [0,2,3]]]

array([[[10, 20, 30],
        [40, 50, 60],
        [ 0,  0,  0]],

       [[10, 20, 30],
        [ 0,  0,  0],
        [ 0,  0,  0]]])

In [208]:
arr3[0:,[0,1,2]]

array([[[10, 20, 30],
        [40, 50, 60],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 1,  2,  3],
        [ 0,  0,  0]]])

### 2. 슬라이싱 : 여러 개의 요소에 대해 참조
- axis 별로 범위 지정
    - from_index : 시작 인덱스(포함), 0일 경우 생략 가능
    - to_index : 종료 인덱스(미포함), 마지막 인덱스일 경우 생략 가능
    - step : 연속되지 않은 범위의 경우 간격 지정
- 열만 조회하는 경우 : 전체 행에 슬라이싱으로 접근 후 특정 열을 조회

In [209]:
# 0 부터 23까지 1씩 증가하는 정수값을 가지는 1차원 배열 생성
a = np.arange(0, 24)
np_print(a)


    type : <class 'numpy.ndarray'>
    shape : (24,)
    dimension : 1
    dtype : int32
    data :
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
    


In [210]:
# 1차원 배열 슬라이싱 : 1번부터 4번까지 접근
a[1:5]

array([1, 2, 3, 4])

In [211]:
# 1번째 인덱스로부터 14번째 인덱스까지 2개씩 건너뛰며 접근
a[1:15:2]

array([ 1,  3,  5,  7,  9, 11, 13])

In [212]:
# 2차원 배열 생성
b = a.reshape(6,4)
np_print(b)


    type : <class 'numpy.ndarray'>
    shape : (6, 4)
    dimension : 2
    dtype : int32
    data :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
    


In [213]:
# 2차원 배열 슬라이싱 : 1행부터 4행까지 접근
# 로우우선 
# 2차원_array [행(:열:간격)]
b[0:4]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [214]:
# 1행부터 4행에 대해 2열부터 3열 까지 접근
b[1:5, 2:4]

array([[ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [215]:
# 2차원 배열 슬라이싱을 통한 값 수정
# 1행부터 4행에 대해 2열부터 3열까지 모든 배열에 대해서 수정
s_arr = b[1:5, 2:4]
s_arr

array([[ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [216]:
# 0번째 행과 마지막 열을 제외한 모든 값을 99로 수정
s_arr[1:, :-1] = 99
s_arr

array([[ 6,  7],
       [99, 11],
       [99, 15],
       [99, 19]])

In [217]:
# 얕은복사로 인한 원본 배열의 변경
# s_arr 의 변경으로 인한 오리지널 b도 같이 변경됨
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 99, 11],
       [12, 13, 99, 15],
       [16, 17, 99, 19],
       [20, 21, 22, 23]])

In [218]:
# 2차원 배열 슬라이싱 : 연속되지 않은 범위의 열에 대한 인덱싱
# step1. 전체 행에 대해서 접근
# step2. 여러 개의 열 인덱싱 배열 전달
# bd의 전체 행 + 1, 3번째 열
# b[행, 열]
b[:, [1,3]]

# 다른 방법
# b[:, 1:4:2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19],
       [21, 23]])

### 연습문제
아래 정보는 학생들의 학번, 영어 성적, 국어 성적, 수학 성적 정보 입니다. <br>
해당 정보를 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 국어 성적, <br>
네번째 행에 수학 성적을 저장한 배열로 만들고 학생별로 영어 성적을 오름차순 기준으로 각 열(column)을 정렬하세요.

<img src='img/sort_q1.png' align='left'>

In [219]:
data = [[1, 2, 3, 4],
       [70, 97, 45, 56],
       [87, 84, 33, 67],
       [46, 80, 75, 78]]
arr = np.array(data)

In [220]:
# 힌트 : argsort()이용
i = np.argsort(arr[1])
np.argsort(arr[1])


array([2, 3, 0, 1], dtype=int64)

In [221]:
arr[:,i]

array([[ 3,  4,  1,  2],
       [45, 56, 70, 97],
       [33, 67, 87, 84],
       [75, 78, 46, 80]])

In [222]:
arr[:,np.argsort(arr[1])]

array([[ 3,  4,  1,  2],
       [45, 56, 70, 97],
       [33, 67, 87, 84],
       [75, 78, 46, 80]])