### 벡터 연산
- 요소들에 대한 연산을 벡터 연산으로 처리하면 일반적인 for 반복문으로

  연산 작업을 처리 하는 것 보다 월등히 뛰어난 처리 속도로 효율적인 작업 가능

In [1]:
import numpy as np

In [2]:
# 0부터 시작하여 1억개 요소를 가진 배열 생성
x = np.arange(100000000)
x

array([       0,        1,        2, ..., 99999997, 99999998, 99999999])

In [3]:
%%time
# 해당 셀을 수행하는데 소요된 시간을 표기해주는 주피터 노트북 명령어
# 셀의 가장 상단에 위치해야함(주석 포함해서 가장 상단에 위치함)

# 반복문을 통한 합계(x변수에 저장한 넘파이 배열 자료 총합 구하기)
# 시간단위 : 1s = 1,000ms(밀리세컨드) = 1,000,000㎲(마이크로 세컨드)

loop_result = 0
for i in x:
    loop_result += i
print(loop_result)



<timed exec>:9: RuntimeWarning: overflow encountered in long_scalars


887459712
Wall time: 20.9 s


In [4]:
# numpy는 연산코어가 C로 되어있어 
# 연산이 Ptyhon 보다 빠릅니다.
%%time
x.sum()

UsageError: Line magic function `%%time` not found.


In [5]:
%%time
np.sum(x)

Wall time: 44 ms


887459712

In [6]:
### (공통) 라이브러리 불러오기 및 사용자 함수 정의
import numpy as np

def np_print(nparr):

    print('''
    type : {}
    shape : {}
    dimension : {}
    dtype : {}
    data :\n {}
    '''.format(type(nparr), nparr.shape, nparr.ndim, nparr.dtype, nparr))

### 배열 정렬
- sort(axis = -1) 메서드 : axis를 기준으로 요소를 오름차순 정렬
    - 기본값(axis = -1) : 현재 배열의 마지막 axis
    - axis = 0 : 열 단위 정렬
    - axis = 1 : 행 단위 정렬
    - 원본 객체에 정렬 결과가 반영됨
- np.sort(axis = -1) : axis를 기준으로 요소를 오름차순 정렬
    - 기본값(axis = -1) : 현재 배열의 마지막 axis
    - axis = 0 : 열 단위 정렬
    - axis = 1 : 행 단위 정렬
    - 정렬된 새로운 배열을 반환함
- np.argsort(arr) : 정렬 순서를 반환
    - 기본값(axis = -1) : 현재 배열의 마지막 axis
    - axis = 0 : 열 단위 정렬
    - axis = 1 : 행 단위 정렬

In [7]:
# 1차원 배열 생성
x = np.arange(0, 5)
np_print(x)


    type : <class 'numpy.ndarray'>
    shape : (5,)
    dimension : 1
    dtype : int32
    data :
 [0 1 2 3 4]
    


In [8]:
# 기본 파이썬 문법으로 순번 뒤집기
# reverse는 파이썬에 적용되는것이라 넘파이의 순번뒤집기와는 다를 수 있음
x[::-1]

array([4, 3, 2, 1, 0])

In [9]:
# 난수 패턴 고정 랜덤시드 20
np.random.seed(20)

In [10]:
a = np.random.randint(0,10,5)
np_print(a)


    type : <class 'numpy.ndarray'>
    shape : (5,)
    dimension : 1
    dtype : int32
    data :
 [3 9 4 6 7]
    


In [11]:
# 1. np.sort(자료) -> 원본에 반영 X
np.sort(a)

array([3, 4, 6, 7, 9])

In [12]:
# 원본에는 영향이 가지 않음을 확인할 수 있습니다.
a

array([3, 9, 4, 6, 7])

In [13]:
# 2. array.sort() -> 원본 자료 변경
a.sort()
a

array([3, 4, 6, 7, 9])

In [14]:
# 원본자료도 같이 변경됨을 확인했습니다.
a

array([3, 4, 6, 7, 9])

In [15]:
b = np.random.randint(0, 10, 5)
np_print(b)
# 역시 난수라 정렬이 안됨을 볼 수 있습니다.


    type : <class 'numpy.ndarray'>
    shape : (5,)
    dimension : 1
    dtype : int32
    data :
 [2 0 6 8 5]
    


In [16]:
# np.argsort(자료)는 내부의 아이템들을 오름차순 정렬하기 위해
# 현재 몇 번 인덱스에 있는 자료를 어디에 배치해야 하는지 보여줌
np.argsort(b)
# array([1, 0, 4, 2, 3], dtype=int64)
# [0, 2, 5, 6, 8] 이 되려면 각각 몇 번 위치로 이동해야하는가를 보여줍니다.

array([1, 0, 4, 2, 3], dtype=int64)

In [17]:
# 0이상 1미만의 범위에서 무작위로 실수값을 가지는 3행 3열의 배열 2개 생성
a = np.random.random((3,3))
b = np.random.random((3,3))

np_print(a)
print('-'*50)
np_print(b)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    dimension : 2
    dtype : float64
    data :
 [[0.65795147 0.19385022 0.2723164 ]
 [0.71860593 0.78300361 0.85032764]
 [0.77524489 0.03666431 0.11669374]]
    
--------------------------------------------------

    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    dimension : 2
    dtype : float64
    data :
 [[0.7512807  0.23921822 0.25480601]
 [0.85762553 0.94977903 0.56168686]
 [0.17878052 0.77025193 0.49238104]]
    


##### 예) 2차원 배열의 경우
기본값 axis = -1 <br>
현재 배열의 axis = 0, 1 <br>
마지막 axis = 1 (행(row)별 정렬)

<img src='img/sortaxis1.jpg' width='200' height='200' align='left'>

In [18]:
# 기본 방향(axis = -1) -> 행(row)별 정렬
np_print(a)
np.sort(a)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    dimension : 2
    dtype : float64
    data :
 [[0.65795147 0.19385022 0.2723164 ]
 [0.71860593 0.78300361 0.85032764]
 [0.77524489 0.03666431 0.11669374]]
    


array([[0.19385022, 0.2723164 , 0.65795147],
       [0.71860593, 0.78300361, 0.85032764],
       [0.03666431, 0.11669374, 0.77524489]])

##### axis = 0 (열별(column) 정렬)

<img src='img/sortaxis0.jpg' width='200' height='200' align='left'>`

In [20]:
# (axis = 0) -> 열(column)별 정렬
np_print(a)
np.sort(a, axis = 0)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    dimension : 2
    dtype : float64
    data :
 [[0.65795147 0.19385022 0.2723164 ]
 [0.71860593 0.78300361 0.85032764]
 [0.77524489 0.03666431 0.11669374]]
    


array([[0.65795147, 0.03666431, 0.11669374],
       [0.71860593, 0.19385022, 0.2723164 ],
       [0.77524489, 0.78300361, 0.85032764]])