In [1]:
import numpy as np

In [2]:
# Numpy 객체 정보를 확인하기 위한 사용자 함수 정의 : 객체타입, 구조, 차원, 데이터타입
def np_print(arr):
    text="""
    type : {}
    shape : {}
    dimension : {}
    dtype : {}
    data : \n {}""".format(type(arr), arr.shape, arr.ndim, arr.dtype, arr)
    print(text)

#### 산술연산
- 더하기 : +, add()
- 빼기 : -, subtract()
- 나누기 : /, divide()ㅁ
- 곱하기 : *, multiply()
- 지수곱 표현 : exp()
- 제곱근 : sqrt()
- 로그 : log()
- 내적(행렬곱) : dot()

In [3]:
# 1부터 10미만의 범위(지정범위)에서 1씩 증가하는 숫자를 데이터로 가진 3행3열 배열
a = np.arange(1,10)
np_print(a)


a = np.arange(1,10).reshape(3,3)
np_print(a)


    type : <class 'numpy.ndarray'>
    shape : (9,)
    dimension : 1
    dtype : int32
    data : 
 [1 2 3 4 5 6 7 8 9]

    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    dimension : 2
    dtype : int32
    data : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# 4이상 13미만의 범위에서 1씩 증가하는 숫자를 데이터로 가진 3행 3열 배열 생성
b = np.arange(4,13).reshape(3,3)
np_print(b)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    dimension : 2
    dtype : int32
    data : 
 [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
# 10~21 까지 3행 4열로 만들기
c = np.arange(10,22).reshape(3,4)
np_print(c)


    type : <class 'numpy.ndarray'>
    shape : (3, 4)
    dimension : 2
    dtype : int32
    data : 
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


#### 배열 더하기
    - 배열 + 배열
    - np.add(arr1, arr2)

In [6]:
print(a)
print('-' * 50)
print(b)
print('-' * 50)
print(a+b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------------------------------------
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
--------------------------------------------------
[[ 5  7  9]
 [11 13 15]
 [17 19 21]]


In [7]:
# +없이 add 메서드 를 써도 됩니다.
np.add(a,b)

array([[ 5,  7,  9],
       [11, 13, 15],
       [17, 19, 21]])

In [8]:
# 구조가 다른 배열끼리의 연산
# a + c

#### 빼기
    - 배열 - 배열
    - np.subtract(arr1, arr2)

In [9]:
a-b

array([[-3, -3, -3],
       [-3, -3, -3],
       [-3, -3, -3]])

In [10]:
b-a

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [11]:
# subtract 메서드 이용
np.subtract(a, b)

array([[-3, -3, -3],
       [-3, -3, -3],
       [-3, -3, -3]])

#### 나누기
    - 배열 / 배열
    - np.divide(arr1, arr2)

In [12]:
# 극한으로 1에 가까워집니다.
a / b

array([[0.25      , 0.4       , 0.5       ],
       [0.57142857, 0.625     , 0.66666667],
       [0.7       , 0.72727273, 0.75      ]])

In [13]:
b / a

array([[4.        , 2.5       , 2.        ],
       [1.75      , 1.6       , 1.5       ],
       [1.42857143, 1.375     , 1.33333333]])

In [14]:
# divide 메서드 이용
np.divide(a, b)

array([[0.25      , 0.4       , 0.5       ],
       [0.57142857, 0.625     , 0.66666667],
       [0.7       , 0.72727273, 0.75      ]])

#### 곱셈
    - 배열 * 배열
    - np.multiply(arr1, arr2)

In [15]:
a * b

array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

In [16]:
np.multiply(a,b)

array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

### 지수곱 표현
- 지수(exponent) : 부동 소수점으로 숫자를 표시할 때 거듭제곱을 사용하여 표현. <br>
(예) 2.14e+2 = 2.14 x 102 = 214 / 2.98e-8 = 2.98 x 10-8 = 0.0000000298
- np.exp(arr) : 밑(base)이 자연상수 e 인 지수함수로 변환(y = e**x)

tip : https://bigpel66.oopy.io/library/c/chewing-c/4

In [17]:
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

### 제곱근
- np.sqrt(arr)

<img src='img/sqrt.gif' width='600' height='200' align='left'>

In [18]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

### 내적(행렬곱)
- np.dot(a, b)

<img src='img/dotProduct.png' width='400' height='200' align='left'>

In [19]:
a * b

array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

In [20]:
print(a) 
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [21]:
np.dot(a,b)

array([[ 48,  54,  60],
       [111, 126, 141],
       [174, 198, 222]])

### Numpy 배열 연산
#### 2. 비교연산

1) 요소
    - 값에 대한 비교 : ==, !=
    - 크기에 대한 비교 : >, <, >=, <=

2) 배열
    - 두 배열 전체에 대한 비교 : array_equal(a,b)

In [22]:
print(a)
print(b)

print( '-' * 50)

print(a==b)
print(a!=b)
print(a>b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
--------------------------------------------------
[[False False False]
 [False False False]
 [False False False]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[False False False]
 [False False False]
 [False False False]]


In [23]:
# 두 배열이 완전히 일치하는지 알고싶을 떄는??
np.array_equal(a,b)

False

### Numpy 배열 연산
3. 집계 함수
    - Numpy 배열에 대해 집계 함수를 적용할 때는 반드시 axis로 설정된 기준에 따라 연산 수행
    - 별도로 값을 지정하지 않으면 기본값은 axis = None으로 지정
    - axis
        - axis = None <br>
        전체 데이터를 하나의 배열로 간주하고 집계 함수의 연산 범위를 전체 배열로 지정
        <br>
        <img src='img/axis_None.jpg' width='150' height='150' align='left'>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        - axis = 0 <br>
        열을 기준으로 동일한 열에 있는 요소를 하나의 그룹으로 묶어 집계 함수의 연산 범위로 지정
        <br>
        <img src='img/axis_0.jpg' width='150' height='150' align='left'>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        - axis = 1 <br>
        행을 기준으로 동일한 행에 있는 요소를 하나의 그룹으로 묶어 집계 함수의 연산 범위로 지정
        <br>
        <img src='img/axis_1.jpg' width='150' height='150' align='left'>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
    - 집계 함수 : 배열객체에 대한 메소드로 사용하거나 Numpy 라이브러리의 메소드로 사용하는 두 가지 방법
        - 합계 : sum()
        - 최소값 : min()
        - 최대값 : max()
        - 누적 합계 : cumsum()
        - 평균 : mean()
        - 중앙값 : median()
            - 크기 순으로 나열된 데이터에 대해 중앙에 위치하는 값
        - 상관계수 : corrcoef()
            - 데이터 간의 상관관계를 나타내는 수치(-1 <= r <= 1)
        - 표준편차 : std()
            - 분산의 제곱근, 데이터가 평균으로부터 흩어져 있는 정도
            - 분산 = 편차(요소-전체평균)제곱의 평균
        - 고유값 : unique()

In [25]:
# 사용할 배역 객체 확인
np_print(a)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    dimension : 2
    dtype : int32
    data : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
# 합계 - 전체기준 -> 모든 요소에 대한 합
# 1) 배열 타입의 메서드 : arr.sum()
# 2) numpy 함수 : np,sum(arr)

# a전체범위 합
print(a.sum())
print(np.sum(a))


45
45


In [30]:
# 합계 - row -> 가로축별 합산
# 메서드, np함수의 파라미터 값 : axis = 1
# 결과값 : [0번 row의 합, 1번 row의 합, 2번 row의 합...]
print(c)
print(c.sum(axis = 1))

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[46 62 78]


In [32]:
# 합계 - column -> 세로축별 합산
# 메서드, np함수의 파라미터 값 : axis = 0
# 결과값 : [0번 column의 합, 1번 column의 합, 2번 column의 합...]
print(c)
print(c.sum(axis = 0))

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[42 45 48 51]


In [39]:
# 최소값 - 전체, 가로, 세로 
# 1) 배열 타입의 메서드 : arr.min()
# 2) numpy 함수 : np.min(arr)
print(np.min(c))
print(c.min())

10
10


In [37]:
# (참고) 파이썬 리스트에서 최소값 찾기
# 팁 : 파이썬 min속도보다 Numpy min이 속도 더 빠른 편
x = [1,2,3,4]
min(x)

1

In [38]:
# 최소값 - 각 가로축(row)별 최소값 찾기
# 결과값 : [0번째 row 최소값, 1번쨰 row 최소값..]
print(c.min(axis = 1))

print(c)

print(np.min(c, axis = 1))

[10 14 18]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[10 14 18]


In [41]:
# 최소값 - 각 세로축(column)별 최소값 찾기
# 결과값 : [0번째 column 최소값, 1번쨰 column 최소값..]

print(c.min(axis = 0))

print(c)

print(np.min(c, axis = 0))

[10 11 12 13]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[10 11 12 13]


In [43]:
# 최대값 - 전체, 가로, 세로 
# 1) 배열 타입의 메서드 : arr.max()
# 2) numpy 함수 : np.max(arr)
# 최대값 - 각 가로세로축(row, column)별 최소값 찾기
# 결과값 : [0번째 (row,column) 최소값, 1번쨰 (row,column) 최소값..]
c.max()
np.max(c)


21

In [46]:
print(c)

print('-'*50)

print(c.max(axis = 0))
print(np.max(c, axis = 0))

print('-'*50)

print(c.max(axis = 1))
print(np.max(c, axis = 1))

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
--------------------------------------------------
[18 19 20 21]
[18 19 20 21]
--------------------------------------------------
[13 17 21]
[13 17 21]


In [48]:
# 누적합계 - 전체 기준
# 1) 배열타입의 메서드 : c.cumsum()
# 2) numpy 함수 : np.cumsum()
# 결과값 :

In [49]:
print(c.sum())
print(c.cumsum())

186
[ 10  21  33  46  60  75  91 108 126 145 165 186]


In [53]:
# 누적합계 - 가로축 기준
print(c.cumsum(axis = 1))
print(np.cumsum(c, axis = 1))

print('-'*40)

# 누적합계 - 세로축 기준
print(c.cumsum(axis = 1))
print(np.cumsum(c, axis = 1))

[[10 21 33 46]
 [14 29 45 62]
 [18 37 57 78]]
[[10 21 33 46]
 [14 29 45 62]
 [18 37 57 78]]
----------------------------------------
[[10 21 33 46]
 [14 29 45 62]
 [18 37 57 78]]
[[10 21 33 46]
 [14 29 45 62]
 [18 37 57 78]]


In [56]:
# 평균 - 전체 기준
# 1) 배열타입의 메서드 : arr.mean()
# 2) numpy 함수 : np.mean(arr)
print(c.mean())
print(np.mean(c))

15.5
15.5


In [55]:
print(c)
print('-'*50)
# 평균 - 가로축 기준
print(c.mean(axis = 1))
print(np.mean(c, axis = 1))

print('-'*50)

# 평균 - 세로축 기준
print(c.mean(axis = 0))
print(np.mean(c, axis = 0))

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
--------------------------------------------------
[11.5 15.5 19.5]
[11.5 15.5 19.5]
--------------------------------------------------
[14. 15. 16. 17.]
[14. 15. 16. 17.]


In [57]:
# 중앙값 - 전체 기준
# numpy 함수 np.median()
# arr.median()사용 불가
# c.median()불가능
np.median(c)

15.5

In [61]:
print(c)
print(np.mean(c, axis = 1))
print(np.median(c, axis = 1))

print('-'*50)

print(c)
print(np.mean(c, axis = 0))
print(np.median(c, axis = 0))

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[11.5 15.5 19.5]
[11.5 15.5 19.5]
--------------------------------------------------
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[14. 15. 16. 17.]
[14. 15. 16. 17.]
