#### 상관계수 : 두 데이터 간의 상관관계(양/음 의 상관관계)
#### numpy함수 : np.corrcoef(arr1, arr2)

In [13]:
import numpy as np

def np_print(arr):
    text="""
    type : {}
    shape : {}
    dimension : {}
    dtype : {}
    data : \n {}""".format(type(arr), arr.shape, arr.ndim, arr.dtype, arr)
    print(text)

In [14]:
a = np.arange(1,10)
np_print(a)


a = np.arange(1,10).reshape(3,3)
np_print(a)


    type : <class 'numpy.ndarray'>
    shape : (9,)
    dimension : 1
    dtype : int32
    data : 
 [1 2 3 4 5 6 7 8 9]

    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    dimension : 2
    dtype : int32
    data : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
x = np.array([15, 12, 27, 37, 29])
y = np.array([1, 4, 2, 9, 7])

In [16]:
print(x)
print(y)
print(np.corrcoef(x,y))

[15 12 27 37 29]
[1 4 2 9 7]
[[1.         0.72615657]
 [0.72615657 1.        ]]


In [17]:
# numpy에서 3개 요소를 이용한 상관도를 구하는 것이 불가능
# pandas를 이용하는 경우 2개씩 짝지은 모든 경우의 수를 구함
z = np.array([0.3, 0.5, 0.6, 0.8, 1.3])
# np.corrcoef(x,y,z)
# 3개의 인자는 받을 수 없습니다.

In [18]:
# 표준편차 - 전체 기준
# 1) 배열 타입의 메서드 : arr.std()
# 2) numpy함수 : np.std(arr)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
# 전체
print(a.std())
print(np.std(a))

print('-'*50)

# 세로축
print(a.std(axis = 0))
print(np.std(a, axis = 0))

print('-'*50)

# 세로축
print(a.std(axis = 1))
print(np.std(a, axis = 1))

2.581988897471611
2.581988897471611
--------------------------------------------------
[2.44948974 2.44948974 2.44948974]
[2.44948974 2.44948974 2.44948974]
--------------------------------------------------
[0.81649658 0.81649658 0.81649658]
[0.81649658 0.81649658 0.81649658]
