### 생성 및 초기화
1. 초기값을 지정하여 데이터를 자동으로 가지는 배열생성
    
    - np.zeros()
    - np.ones()
    - np.full()
    - np.eye()
    - np.empty()

In [14]:
# 이산수학 관련 공부 선형대수, 벡터, 기하, 확통

#### 1-1 np.zeros(shape(모양), dtype = float) -> 영(0)행렬을 만드는 기능

- 지정된 구조의 배열을 생성하고 모든 요소를 0으로 초기화(zeros)
- shape : tuple형태로 행, 열을 지정
- dtype : 배열에서 사용하는 데이터 타입을 지정, 기본값은 numpy.float64

In [15]:
import numpy as np

def np_print(arr):
    text = '''
    type : {}
    shape : {}
    ndim : {}
    dtype : {}
    array data : \n {}'''.format(type(arr), arr.shape, arr.ndim, arr.dtype, arr)
    print(text)

In [16]:
# 3행 4열 구조 안에 모든 값이 0으로 채워짐
# 구조는 튜플로 묶어서 넘김

arr = np.zeros((3,4))
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (3, 4)
    ndim : 2
    dtype : float64
    array data : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
# dtype만 float -> int로 바꿔서 생성
arr = np.zeros((3,4), dtype = int)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (3, 4)
    ndim : 2
    dtype : int32
    array data : 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


#### 1-2 np.ones(shape(행, 열), dtype = float)
- 지정된 구조의 배열을 생성하고 모든 요소를 1로(ones) 초기화
- shape : tuple 자료로 행, 열 구조를 가짐
- dtype : 배열의 데이터 타입 지정, 기본값 = numpy.float64

In [18]:
# 3헹 4열 구조 안에서 초기값을 모두 1로 가지는 행렬
arr = np.ones((3,4), dtype = int)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (3, 4)
    ndim : 2
    dtype : int32
    array data : 
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


#### 1-3 np.full(shape, fill_value, dtype)
- 지정된 구조의 배열을 생성하고 모든 요소를 fill_value 값으로 초기화
- shape : tuple 자료형으로 행, 열 구조를 지정
- dtype : 배열의 데이터 타입을 지정, 기본값 = 들어오는 데이터의 자료형

In [19]:
arr = np.full((3, 4), 5, dtype = int)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (3, 4)
    ndim : 2
    dtype : int32
    array data : 
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


#### 1-4 np.eye(N,N = none, dtype = float)
- (N,M) 구조의 단위 행렬을 생성
- M : 열 개수를 지정, 기본값 = N
- dtypr : 배열의 데이터 타입을 지정, 기본값 = numpy.float64

In [20]:
# 3행 3열의 단위행렬
arr = np.eye(4)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (4, 4)
    ndim : 2
    dtype : float64
    array data : 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [21]:
# 세로길이 (row)5, 가로길이3(column)인 단위행렬을 .eye()로 만들어보세요
arr = np.eye(5,3)
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (5, 3)
    ndim : 2
    dtype : float64
    array data : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### 1-5 np.empty(shape, dtype = float)
- 지정된 구조의 배열을 생성하고 모든 요소에 대한 초기화 과정 없이 직전 메모리에 저장된 값을 사용
- 배열을 생성하는데 가장 빠르고 효율적인 방법
- shape : tuple type으로 행, 열 구조를 지정
- dtype : 배열의 데이터 타입을 지정, 기본값 = numpy.float64

In [22]:
# 직전 메모리에 저장된 값을 사용하기 위해서는 직전에 만들었던과 동일한
# shpape의 배열을 생성해야한다.

# 지금 (7,2)행렬은 만든적이 없기 때문에 0으로 채워집니다.

arr = np.empty((7,2))
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (7, 2)
    ndim : 2
    dtype : float64
    array data : 
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [23]:
# 이전에 만들었던 (3,4)가 나올 까요??
arr = np.empty((3,4))
np_print(arr)


    type : <class 'numpy.ndarray'>
    shape : (3, 4)
    ndim : 2
    dtype : float64
    array data : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
