#### 브로드캐스팅(BroadCasting)
- 서로 다른 구조(shape)를 가진 배열에 대해 연산을 수행할 때 구조를 맞추는 과정
- 배열과 스칼라값 간의 연산
- 배열과 배열 간의 연산
- 브로드캐스팅 규칙 : 축의 길이가 일치하거나 둘 중 하나의 길이가 1인 두 배열에 대해 호환성을 가짐

<img src='img/broadcast.png' width='600' height='400' align='left'>

In [3]:
import numpy as np

def np_print(arr):
    text="""
    type : {}
    shape : {}
    dimension : {}
    dtype : {}
    data : \n {}""".format(type(arr), arr.shape, arr.ndim, arr.dtype, arr)
    print(text)

In [5]:
a = np.arange(1,10)
np_print(a)


a = np.arange(1,10).reshape(3,3)
np_print(a)

b = np.arange(4,13).reshape(3,3)
np_print(b)


    type : <class 'numpy.ndarray'>
    shape : (9,)
    dimension : 1
    dtype : int32
    data : 
 [1 2 3 4 5 6 7 8 9]

    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    dimension : 2
    dtype : int32
    data : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    dimension : 2
    dtype : int32
    data : 
 [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [7]:
# 사용할 배열 객체 확인
np_print(a)
np_print(b)
print(a + b)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    dimension : 2
    dtype : int32
    data : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    dimension : 2
    dtype : int32
    data : 
 [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 5  7  9]
 [11 13 15]
 [17 19 21]]


#### 1. 배열과 값(single value, scala)

- 스칼라 값을 배열의 구조와 동일한 배열로 변형하여 연산수행

In [8]:
# 구조가 다른 배열간의 연산
# a배열의 모든 요소에 각각 10씩 더하기
a + 10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [11]:
# 스칼라 -> 배열 변형
# 3행 3열의 구조에 모든 요소가 10인 배열 생성
# a같은 구조에 모두 10값을 넣어주세요
scalar_arr =  np.full_like(a, 10)
np_print(scalar_arr)



    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    dimension : 2
    dtype : int32
    data : 
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [13]:
# 두개 다 똑같은 결과를 보여줍니다.
print(a + scalar_arr)
print(a + 10)

[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


#### 2. 서로 다른 구조의 배열
- 행, 열의 최대 길이를 기준으로 구조을 생성한 배열로 변형하여 연산 수행
- 확장된 행, 열에 대해서 기존 배열과 동일한 데이터로 구성

In [18]:
# 1행 4열의 구조에서 1,2,3,4를 값으로 가지는 배열 x 생성
# 4행 1열의 구조에서 1,2,3,4를 값으로 가지는 배열 y 생성
x = np.arange(1,5).reshape(1,4)
y = np.arange(1,5).reshape(4,1)

In [20]:
np_print(x)
print('-'*50)
np_print(y)


    type : <class 'numpy.ndarray'>
    shape : (1, 4)
    dimension : 2
    dtype : int32
    data : 
 [[1 2 3 4]]
--------------------------------------------------

    type : <class 'numpy.ndarray'>
    shape : (4, 1)
    dimension : 2
    dtype : int32
    data : 
 [[1]
 [2]
 [3]
 [4]]


In [22]:
# 배열 x를 동일한 값으로 4행으로 확장한 새로운 배열 생성
# 행 방향으로 배열 추가(세로길이 증가) 메서드 : np.append(arr1, arr2, axis = 0)

new_x = np.append(x, x, axis = 0)
new_x
# x + x를 한것입니다.

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [27]:
# 위의 new_x를 (4,4)로 만들어 보세요
new_x = np.append(new_x, new_x, axis = 0)
new_x

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [30]:
# 배열  y도 위의 수순대로 4열까지 확장한 새로운 배열로 저장해주세요.
# 열 방향으로(컬럼갯수 증가)배열 추가 메서드 np.append(), axis = 1
new_y = np.append(y, y, axis = 1)
new_y

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [31]:
new_y = np.append(new_y, new_y, axis = 1)
new_y

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

In [32]:
x + y 

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

In [33]:
new_x + new_y

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])